# Generated by Django 4.2 on 2023-05-04 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, null=True, verbose_name='توکن')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('code', models.IntegerField(verbose_name='کد دریافتی')),
                ('expirtion_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رجیستر',
                'verbose_name_plural': 'رجیستر ها',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=12, verbose_name='شماره تلفن')),
                ('address', models.TextField(verbose_name='آدرس کامل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
