# Generated by Django 4.2 on 2023-05-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('subject', models.CharField(max_length=50, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'پیام دریافتی',
                'verbose_name_plural': 'پیام های دریافتی',
            },
        ),
    ]
