# Generated by Django 4.2 on 2023-05-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
    ]
