# Generated by Django 4.2 on 2023-04-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_personalization', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
