# Generated by Django 4.2 on 2023-04-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_personalization', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='آدرس ایمیل'),
        ),
    ]
