# Generated by Django 4.2 on 2023-04-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_personalization', '0007_alter_user_email_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=50, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
