# Generated by Django 4.2 on 2023-04-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_personalization', '0008_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
