# Generated by Django 4.2 on 2023-05-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(related_name='has_parent', to='product.category', verbose_name='زیر مجموعه'),
        ),
    ]
