# Generated by Django 4.2 on 2023-05-08 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='credited',
            new_name='created',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='عنوان صفحه'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='product.category', verbose_name='زیر مجموعه'),
        ),
    ]
