# Generated by Django 4.2 on 2023-05-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
